# MoveIt uses this configuration for controller management

moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

moveit_simple_controller_manager:
  controller_names:
    - moveit_controller

  moveit_controller:
    type: FollowJointTrajectory
    joints:
      []
    action_ns: follow_joint_trajectory
    default: true