
command_in_type: "unitless"
scale:
 
  linear:  0.4  
  rotational:  0.8 
  joint: 0.5

publish_period: 0.034 
low_latency_mode: false 
command_out_type: trajectory_msgs/JointTrajectory

publish_joint_positions: true
publish_joint_velocities: true
publish_joint_accelerations: false

low_pass_filter_coeff: 2.0 

move_group_name: arm  
planning_frame: base_link 

ee_frame_name: tool0 
robot_link_command_frame: base_link  

incoming_command_timeout:  0.1 
num_outgoing_halt_msgs_to_publish: 4

lower_singularity_threshold:  17.0
hard_stop_singularity_threshold: 30.0
joint_limit_margin: 0.1 

cartesian_command_in_topic: ~/delta_twist_cmds 
joint_command_in_topic: ~/delta_joint_cmds 
joint_topic: /joint_states
status_topic: /servo_node/status
command_out_topic: /arm_controller/joint_trajectory 

check_collisions: true 
collision_check_rate: 10.0 
collision_check_type: threshold_distance
self_collision_proximity_threshold: 0.01 
scene_collision_proximity_threshold: 0.02 
collision_distance_safety_factor: 1000.0
min_allowable_collision_distance: 0.01
