controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    hardware_plugin: gazebo_ros2_control/GazeboSystem
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - J1
        - J2
        - J3
        - J4
        - J5
        - J6

      state_publish_rate: 25.0
      action_monitor_rate: 10.0
      constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        J1: { trajectory: 0.2, goal: 0.1 }
        J2: { trajectory: 0.2, goal: 0.1 }
        J3: { trajectory: 0.2, goal: 0.1 }
        J4: { trajectory: 0.2, goal: 0.1 }
        J5: { trajectory: 0.2, goal: 0.1 }
        J6: { trajectory: 0.2, goal: 0.1 }

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

arm_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
    command_interfaces:
      - position
      - velocity
    state_interfaces:
      - position
      - velocity