controller_manager:
  ros__parameters:
    update_rate: 100  # Hz
    hardware_plugin: gazebo_ros2_control/GazeboSystem
    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController
      joints:
        - J1
        - J2
        - J3
        - J4
        - J5
        - J6
      state_publish_rate: 50
      action_monitor_rate: 10
      constraints:
        goal_time_tolerance: 5.0
        stopped_velocity_tolerance: 0.01
        J1: { trajectory: 0.05, goal: 0.05 }
        J2: { trajectory: 0.05, goal: 0.05 }
        J3: { trajectory: 0.05, goal: 0.05 }
        J4: { trajectory: 0.05, goal: 0.05 }
        J5: { trajectory: 0.05, goal: 0.05 }
        J6: { trajectory: 0.05, goal: 0.05 }

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
      publish_rate: 50

arm_controller:
  ros__parameters:
    joints:
      - J1
      - J2
      - J3
      - J4
      - J5
      - J6
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
